name: Build & publish image

on:
  workflow_call:
    inputs:
      docker-registry:
        type: string
        default: ghcr.io
      image-namespace:
        required: true
        type: string
      image-repo:
        required: true
        type: string
      labels:
        type: string
      platforms:
        type: string
        default: linux/amd64,linux/arm64
      release:
        type: boolean
        default: true
    secrets:
      registry-password:
        required: true
      registry-username:
        required: true

jobs:
  build:
    name: Build & publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Debug on runner (When re-run with "Enable debug logging" checked)
        if: runner.debug
        uses: mxschmitt/action-tmate@a283f9441d2d96eb62436dc46d7014f5d357ac22 # v3.17
        with:
          detached: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3.1.0
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: ${{ inputs.docker-registry }}/${{ inputs.image-namespace }}/${{ inputs.image-repo }}
          labels: ${{ inputs.labels }}
      - name: Log in to registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ inputs.docker-registry }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}
      - name: Build and push Docker image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: .
          platforms: ${{ inputs.platforms }}
          push: ${{ inputs.release }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
